### ISSUE TITLE
Test plus ones!

### ISSUE THREAD

**Issue by ukd1** [ukd1/plusone#1]
Everyone loves plus ones. Note, this takes a minute or two to update due to caching.

[![Issue #1](http://plusone-demo.herokuapp.com/count.svg?repo=ukd1/plusone&issue=1&sig=fcc82e36f38a2246df3732679c145b8061a282738d07192b22bda48b67114d04029cb2386f330f89639a2028c8fe021ef09985aa72a80b946589c8a1875e744e)](https://github.com/ukd1/plusone/issues/1)

This is a test badge. Plus fee free to try and +1 it!

**Comment by shosti** [comment]
+2

**Comment by shosti** [comment]
+1

**Comment by shosti** [comment]
:

**Comment by shosti** [comment]
:+1:

**Comment by prayogoa** [comment]
+1

**Comment by usami** [comment]
+100

**Comment by usami** [comment]
+1

**Comment by ukd1** [comment]
Lol @usami...

**Comment by mchenryc** [comment]
Not working on Chrome, Android

**Comment by ukd1** [comment]
@mchenryc it's SVG; maybe that's why? What's the error?

**Comment by andrewsuzuki** [comment]
I noticed @shosti's :+1: wasn't counted for some reason. Hmm, are emojis not included in the comment body on the receiving end? If not, how can both `:+1:` and `:thumbsup:` be included?

**Comment by aemadrid** [comment]
+1

**Comment by mchenryc** [comment]
@ukd1 with apologies, it was not Chrome, but the embedded browser of an app (a HN reader). The image displayed as a broken image tag, with the "Issue #1" alt-text displayed. If the alt-text were the +1 count, that would probably suffice.

**Comment by ukd1** [comment]
@mchenryc cool - actually, I can't fix it that way as that part is static in the issue.

I can't fix the image without moving away from SVG...

**Comment by ukd1** [comment]
@andrewsuzuki probably the server was offline...

**Comment by ukd1** [comment]
@andrewsuzuki it only counts one user id's +1 per issue.

+1 and :+1: work as they both have +1 in them in raw text :)

**Comment by jipiboily** [comment]
+1.5 ?

**Comment by zaidakram** [comment]
+1 and :+1:

**Comment by ukd1** [comment]
@jipiboily :+1: read the codess....there is no cheating ;)

**Comment by olzaragoza** [comment]
+1
